# Generated by Django 5.2.17 on 2026-10-03 03:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("policy_version", models.CharField(max_length=128)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("sequence", models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ("at", models.DateTimeField()),
                ("actor_id", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=80)),
                ("target_id", models.CharField(max_length=100)),
                ("detail", models.JSONField(default=dict)),
                ("previous_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="AuditHead",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
                ),
                (
                    "last_hash",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        max_length=64,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("scenario", models.CharField(max_length=80)),
                ("status", models.CharField(default="pending", max_length=12)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("checks", models.JSONField(default=list)),
                ("manifest", models.JSONField(default=dict)),
                ("project_ids", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="LogoutReplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("jti", models.CharField(max_length=255, unique=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PolicyState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("version", models.CharField(max_length=128)),
                ("frozen", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AssistantTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("status", models.CharField(default="active", max_length=16)),
                ("calls_used", models.PositiveIntegerField(default=0)),
                ("drafts_created", models.PositiveIntegerField(default=0)),
                ("policy_version", models.CharField(max_length=128)),
                ("resource_ids", models.JSONField(default=list)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.evidencerun"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutboxJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=24)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("desired", models.JSONField(default=dict)),
                ("observed", models.JSONField(default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("lease_until", models.DateTimeField(null=True)),
                ("last_error", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assistant_task",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.assistanttask",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.changerequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Principal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("issuer", models.URLField(max_length=500)),
                ("subject", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("human", "human"), ("agent", "agent")], max_length=10
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("status", models.CharField(default="active", max_length=16)),
                ("roles", models.JSONField(default=list)),
                ("project_ids", models.JSONField(default=list)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sponsored_agents",
                        to="core.principal",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workforce_identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operator_identities",
                        to="core.principal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("fingerprint", models.CharField(max_length=64)),
                ("response", models.JSONField()),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.principal"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="changerequest",
            name="identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_requests",
                to="core.principal",
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_requests",
                to="core.principal",
            ),
        ),
        migrations.AddField(
            model_name="assistanttask",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.principal"
            ),
        ),
        migrations.AddField(
            model_name="assistanttask",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assistant_tasks",
                to="core.principal",
            ),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("project", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("sensitivity", models.CharField(default="internal", max_length=30)),
                ("provider_group", models.CharField(blank=True, max_length=255)),
                ("evidence", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.principal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("permission", models.CharField(default="read", max_length=40)),
                ("status", models.CharField(default="active", max_length=12)),
                ("expires_at", models.DateTimeField(null=True)),
                ("purpose", models.CharField(blank=True, max_length=255)),
                ("max_calls", models.PositiveIntegerField(null=True)),
                ("calls_used", models.PositiveIntegerField(default=0)),
                (
                    "source_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.changerequest",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.principal"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.resource"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="changerequest",
            name="resource",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.resource"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("status", models.CharField(default="open", max_length=20)),
                ("due_at", models.DateTimeField()),
                ("findings", models.JSONField(default=list)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.principal"
                    ),
                ),
                ("resources", models.ManyToManyField(to="core.resource")),
            ],
        ),
        migrations.AddField(
            model_name="assistanttask",
            name="review",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.review"),
        ),
        migrations.CreateModel(
            name="SessionBinding",
            fields=[
                ("session_key", models.CharField(max_length=40, primary_key=True, serialize=False)),
                ("oidc_sid", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.principal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="approval",
                        serialize=False,
                        to="core.changerequest",
                    ),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                ("policy_version", models.CharField(max_length=128)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.principal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SponsorAcceptance",
            fields=[
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="core.changerequest",
                    ),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.principal"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="principal",
            constraint=models.UniqueConstraint(
                fields=("issuer", "subject"), name="unique_issuer_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("principal", "key"), name="unique_principal_idempotency"
            ),
        ),
    ]
