# Generated by Django 5.2.17 on 2026-10-03 05:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_ratebucket"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffboardingCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("employment_type", models.CharField(max_length=12)),
                ("hr_event_id", models.CharField(max_length=64)),
                ("hr_source", models.CharField(max_length=64)),
                ("effective_at", models.DateTimeField()),
                ("due_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=255)),
                ("bindings", models.JSONField(default=list)),
                ("attestations", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(null=True)),
                ("closed_packet", models.JSONField(default=dict)),
                (
                    "closed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_departures",
                        to="core.principal",
                    ),
                ),
                (
                    "containment_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.changerequest",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departure_cases",
                        to="core.principal",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_departures",
                        to="core.principal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlatformImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("captured_at", models.DateTimeField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("report", models.JSONField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.principal"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_imports",
                        to="core.offboardingcase",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="offboardingcase",
            constraint=models.UniqueConstraint(
                fields=("hr_source", "hr_event_id"), name="unique_departure_event"
            ),
        ),
    ]
