# Generated by Django 5.2.17 on 2026-10-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_offboardingcase_platformimport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offboardingcase",
            name="ad_binding",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="ADEnrollment",
            fields=[
                (
                    "identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="ad_enrollment",
                        serialize=False,
                        to="core.principal",
                    ),
                ),
                ("domain_guid", models.UUIDField()),
                ("user_guid", models.UUIDField()),
                ("group_guids", models.JSONField(default=list)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain_guid", "user_guid"), name="unique_ad_directory_person"
                    )
                ],
            },
        ),
    ]
