# Generated by Django 5.2.17 on 2026-10-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_offboardingcase_ad_binding_adenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="offboardingcase",
            name="intake_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intake_departures",
                to="core.principal",
            ),
        ),
        migrations.AlterField(
            model_name="principal",
            name="kind",
            field=models.CharField(
                choices=[("human", "human"), ("agent", "agent"), ("service", "service")],
                max_length=10,
            ),
        ),
    ]
