# Generated by Django 5.2.17 on 2026-10-05 03:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_hr_intake"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("checked_at", models.DateTimeField()),
                ("status", models.CharField(max_length=12)),
                ("successes", models.JSONField(default=list)),
                ("refused", models.PositiveIntegerField(default=0)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_checks",
                        to="core.offboardingcase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                ("jti", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("source_ref", models.CharField(max_length=200, unique=True)),
                ("event_type", models.CharField(max_length=40)),
                ("subject", models.CharField(max_length=255)),
                ("token", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(null=True)),
                ("receiver_error", models.CharField(blank=True, max_length=64)),
                (
                    "case",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_events",
                        to="core.offboardingcase",
                    ),
                ),
            ],
        ),
    ]
