# Generated by Django 5.2.17 on 2026-10-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_signal_receivers"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntraEnrollment",
            fields=[
                (
                    "identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="entra_enrollment",
                        serialize=False,
                        to="core.principal",
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("group_ids", models.JSONField(default=list)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="offboardingcase",
            name="entra_binding",
            field=models.JSONField(default=dict),
        ),
    ]
